#!/bin/bash
#bash script for install sc_framework.
#must run to install.

clear
echo " ---(sc framework installer)--- ";

if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then
    INSTALL_DIR="$PREFIX/usr/share/doc/sc_framework"
    BIN_DIR="$PREFIX/bin/"
    BASH_PATH="$PREFIX/bin/bash"
    TERMUX=true

    pkg install -y git python2
elif [ "$(uname)" = "Darwin" ]; then
    INSTALL_DIR="/usr/local/sc_framework"
    BIN_DIR="/usr/local/bin/"
    BASH_PATH="/bin/bash"
    TERMUX=false
else
    INSTALL_DIR="$HOME/.sc_framework"
    BIN_DIR="/usr/local/bin/"
    BASH_PATH="/bin/bash"
    TERMUX=false

    sudo apt-get install -y git python
fi

echo"[!] Checking directories...";
if [ -d "$INSTALL_DIR" ]; then
    echo "[?] A directory sc_framework was found! Do you want to replace it? [y/n]:" ;
    read -r mama
    if [ "$mama" = "y"  ]; then
        if [ "$TERMUX" = true ]; then
            rm -rf "$INSTALL_DIR"
            rm "$BIN_DIR/sc_framework*"
        else
            sudo rm -rf "$INSTALL_DIR"
            sudo rm "$BIN_DIR/sc_framework*"
        fi
    else
        echo "[x] If you want to install you must remove previous installations [x]";
        echo "[x] Installation faild! [x]";
        exit
    fi
fi
echo "[!] Cleaning up old directories ...";
if [ -d "$ETC_DIR/singlecore" ]; then
    echo "$DIR_FOUND_TEXT"
    if [ "$TERMUX" = true ]; then
        rm -rf "$ETC_DIR/singlecore"
    else
        sudo rm -rf "$ETC_DIR/singlecore"
    fi
fi

echo "[^] Installing...";
echo "";
git clone --depth=1 https://github.com/singlecore06483/sc_framework "$INSTALL_DIR";
echo "#!$BASH_PATH
python $INSTALL_DIR/scconsole.py" "${1+"$@"}" > "INSTALL_DIR/sc_framework";
chmod +x "$INSTALL_DIR/sc_framework";
if [ "$TERMUX" = true ]; then
    cp "$INSTALL_DIR/sc_framework" "$BIN_DIR"
else
    sudo cp "$INSTALL_DIR/sc_framework" "$BIN_DIR"
fi
rm "$INSTALL_DIR/sc_framework"


if [ -d "$INSTALL_DIR" ]
then
    echo "";
    echo "[^] Tool installed successfully! [^]";
    echo "[^]===============================================================================[^]";
    echo "[^]    All is done!! You can execute tool by typing sc_framework or scconsole !   [^]";
    echo "[^]===============================================================================[^]";
    echo "";
else
    echo "[x] Installation faild! [x] ";
    exit
fi
